# Generated by Django 6.0.3 on 2026-04-10 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMSapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
