# Generated by Django 6.0.3 on 2026-04-10 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMSapp', '0002_appointment_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
