# Generated by Django 6.0.3 on 2026-04-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMSapp', '0003_appointment_full_name_appointment_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='Department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
