# Generated by Django 5.2 on 2026-04-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='doctor_status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='experience',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
